---
abstract: 'does your code require newer perl than you think?'
author:
  - 'tokuhirom <tokuhirom@gmail.com>'
build_requires:
  File::Temp: 0
  Test::MinimumVersion: 0
  Test::More: 0.98
  Test::Tester: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.6.5, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-MinimumVersion-Fast
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Test::MinimumVersion::Fast:
    file: lib/Test/MinimumVersion/Fast.pm
    version: 0.03
requires:
  File::Find::Rule: 0
  File::Find::Rule::Perl: 0
  Perl::MinimumVersion::Fast: 0.11
  Test::Builder: 0
  YAML::Tiny: 1.40
  parent: 0
  perl: 5.008005
  version: 0.70
resources:
  bugtracker: https://github.com/tokuhirom/Test-MinimumVersion-Fast/issues
  homepage: https://github.com/tokuhirom/Test-MinimumVersion-Fast
  repository: git://github.com/tokuhirom/Test-MinimumVersion-Fast.git
version: 0.03
